http://localhost:2000/api

###
POST http://localhost:2000/users
Content-Type: application/json

{
  "userName": "Agna N",
  "email" : "agna@mail.com",
  "password" : "Asdasd" 
}

###
POST http://localhost:2000/users/login
Content-Type: application/json

{
        "userName": "Agna N",
        "password": "Asdasd"
    }
    
###
GET http://localhost:2000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IkFnbmEgTiIsImVtYWlsIjoiYWduYUBtYWlsLmNvbSIsImlhdCI6MTY5OTc1MTgxOSwiZXhwIjoxNjk5NzUxODM5fQ.sGWAXcCSfINCZ33QlnP-2UzfRber_6E4U3ctla6HP4s

###
GET http://localhost:2000/token

###
GET http://localhost:2000/users/keeplogin


###
DELETE http://localhost:2000/users/logout
