http://localhost:2000/api

###
POST http://localhost:2000/users
Content-Type: application/json

{
  "userName": "Agna N",
  "email" : "agna@mail.com",
  "password" : "Asdasd" 
}

###
POST http://localhost:2000/users/login
Content-Type: application/json

{
        "userName": "Agna N",
        "password": "Asdasd"
    }
    
###
GET http://localhost:2000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImVtYWlsIjoiYWduYUBtYWlsLmNvbSIsImlhdCI6MTcwMDAzMTQ5NiwiZXhwIjoxNzAwMDMxNTE2fQ.dCLv2qHFAWu1oLYxqA2I-UtU4ZJ_LlBkYU9Yq3JLE1M 

###
GET http://localhost:2000/token

###
GET http://localhost:2000/users/keeplogin


###
DELETE http://localhost:2000/users/logout
